#!/usr/bin/env bash
# Bash script that accepts 4 parameters & transfers a file from our client to a server

# Check if 4 param, if not display usage message
if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# set variables for parameters
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# use scp to transfer file to server
scp -o StrictHostKeyChecking=no -i $PATH_TO_SSH_KEY $PATH_TO_FILE $USERNAME@$IP:~

# exit with status code of last executed command
exit $?
