#!/usr/bin/env bash
# script that installs and configures Nginx on remote server

# Update package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello Wolrd!' > /var/www/html/index.html
sudo service nginx restart
