#!/usr/bin/env bash
# script that installs and configures Nginx on remote server and redirects w/ 301 and add 404 page


# Update package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Create backup of default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Modify configuration file to listen on port 80 and set document root to /var/www/html
sudo sed -i 's/listen\s*80;/listen 80 defualt_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's|#*root /var/www/html;|root /var/www/html;|g' /etc/nginx/sites-available/default
sudo sed -i 's|#*index index.html;|index index.html;|g' /etc/nginx/sites-available/default

# Add redirect rule to configuration file
sudo sed -i 's|location / {|location / {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|g' /etc/nginx/sites-available/default

# Modify configuration file to use custom 404 page
sudo sed -i '/error_page 404/i \\tlocation = /404.html {\n\t\tinternal;\n\t}\n\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
