#!/usr/bin/env bash
# Script displaying a sentence indefinitely with sleep 2 between and i am invincible when receiving a SIGTERM signal
while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
