#!/usr/bin/env bash
# Script displaying 1 to 100 displaying FizzBuzz on diff multiples
for i in {1..100}
do
if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
then
echo "FizzBuzz"
elif [ $((i % 5)) -eq 0 ]
then
echo "Buzz"
elif [ $((i % 3)) -eq 0 ]
then
echo "Fizz"
else
echo "$i"
fi
done
