#!/usr/bin/env bash
# while loop displaying hours from 0-12 and min from 1-59
hour=0
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	min=0
	while [ "$((++min))" -lt 60 ]
	do
		echo "Min: $min"
	done
	hour="$((hour+1))"
done
