#!/usr/bin/env bash
# while loop displaying hours from 0-12 and min from 1-59
i=0
while [ "$i" -le 12 ]
do
	echo "Hour: $i"
	min=1
	while [ "$((min++))" -le 59 ]
	do
		echo "$min"
	done
	i="$((i+1))"
done
