#!/usr/bin/env bash
# If and else statements that gives info about a file
if [ -e school ]
then
	echo "school file exits"
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exits"
fi
